let products = [
    {
        "id": 1001,
        "title": "Agricultural Sciences",
        "description": "Agricultural science is a broad multidisciplinary field of biology that encompasses the parts of exact, natural, economic and social sciences that are used in the practice and understanding of agriculture..",
        "price": 970,
        "location": "Malta",
        "image": "images/product-agric.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1002,
        "title": "Biology",
        "description": "Biology is the natural science that studies life and living organisms, including their physical structure, chemical processes, molecular interactions.",
        "price": 570,
        "location": "Kano",
        "image": "images/product-bio.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1003,
        "title": "Business studies",
        "description": "Business studies is an academic subject taught in schools and at university level in many countries.",
        "price": 300,
        "location": "Abuja",
        "image": "images/product-business.jpg",
        "availableInventory": 5, 
        "rating": 2,
    },
    {
        "id": 1004,
        "title": "Chemistry",
        "description":  "Chemistry, the science of the properties, composition, and structure of substances (defined as elements and compounds), the transformations they undergo.",
        "price": 230,
        "location": "USA",
        "image": "images/product-chem.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1005,
        "title": "Data Processing",
        "description":"Data processing occurs when data is collected and translated into usable information.",
        "price": 160,
        "location": "Abuja",
        "image": "images/product-data.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1006,
        "title": "Languages",
        "description": "A language is a structured system of communication used by humans consisting of speech.",
        "price": 170,
        "location": "Malta",
        "image": "images/product-english.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1007,
        "title": "Further Mathemaics",
        "description": "Further Mathematics is the title given to a number of advanced secondary mathematics courses.",
        "price": 900,
        "location": "London",
        "image": "images/product-fmaths.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1008,
        "title": "History",
        "description": "History is the study of the past. Events occurring before the invention of writing systems are considered prehistory.",
        "price": 190,
        "location": "London",
        "image": "images/product-history.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1009,
        "title": "Photography",
        "description": "Photography is the art, application, and practice of creating durable images by recording light, either electronically by means of an image sensor, or chemically by means of a light-sensitive material such as photographic film.",
        "price": 295,
        "location": "Abuja",
        "image": "images/product-photo.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1010,
        "title": "Technical drawing",
        "description": "Technical drawings are blue print style drawings that display a products information, from dimensions like height, width and depth, to specified information such as materials or assembly details.",
        "price": 188,
        "location": "Kano",
        "image": "images/product-tech.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
]